### ISSUE TITLE
Type Error on import twain

### ISSUE THREAD

**Issue by furqanazhar** [denisenkom/pytwain#42]
```python
import twain
``` 

Traceback (most recent call last):
  File "C:\Users\DELL\PycharmProjects\DocScanner1\main.py", line 1, in <module>
    import twain
  File "C:\Users\DELL\PycharmProjects\DocScanner1\venv\lib\site-packages\twain\__init__.py", line 12, in <module>
    from .lowlevel.structs import *
  File "C:\Users\DELL\PycharmProjects\DocScanner1\venv\lib\site-packages\twain\lowlevel\structs.py", line 174, in <module>
    def frame2tuple(frame: TW_FRAME) -> tuple[float, float, float, float]:
TypeError: 'type' object is not subscriptable

**Comment by denisenkom** [comment]
What is your Python version?  You are probably using unsupported version, oldest supported version is 3.8

**Comment by furqanazhar** [comment]
Preivously, I had python 3.8 installed but still same issue so i upgraded to python 3.12 and got it running. But now when i click scan button, below error pops up, can you help me here?

```python
INFO:twain:attempting to load dll: twaindsm.dll
ERROR:twain:load failed with error Could not find module 'twaindsm.dll' (or one of its dependencies). Try using the full path with constructor syntax
```

**Comment by denisenkom** [comment]
Here https://pytwain.readthedocs.io/en/latest/ you can find some information on how to install twaindsm.dll
