### ISSUE TITLE
Twain Module Raise an Exception : twain.excTWCC_SEQERROR

### ISSUE THREAD

**Issue by yazilimci1** [denisenkom/pytwain#7]
I can connect scanner and scan multiple files . The code is below.
```
import twain

sm = twain.SourceManager(0)
ss = sm.OpenSource()
ss.RequestAcquire(0,0)

while True:
    rv = ss.XferImageNatively()
    if rv is None:
        break
    else:
        (handle, count) = rv
        twain.DIBToBMFile(handle, '{}.bmp'.format(uuid.uuid4()))
}
```
After scanning operation has finished , the images saved .bmp files but the program throws an exception message and the program can't execute the other lines of code.

```
C:\Python34\python.exe C:/Users/PB/PycharmProjects/34Deneme/dene.py
Traceback (most recent call last):
  File "C:/Users/PB/PycharmProjects/34Deneme/dene.py", line 13, in <module>
    rv = ss.XferImageNatively()
  File "C:\Python34\lib\site-packages\twain.py", line 1841, in XferImageNatively
    rv, handle = self._get_native_image()
  File "C:\Python34\lib\site-packages\twain.py", line 1787, in _get_native_image
    (TWRC_XFERDONE, TWRC_CANCEL))
  File "C:\Python34\lib\site-packages\twain.py", line 1453, in _call
    return self._sm._call(self._id, dg, dat, msg, buf, expected_returns)
  File "C:\Python34\lib\site-packages\twain.py", line 2094, in _call
    raise exc
twain.excTWCC_SEQERROR
Exception ignored in: <bound method SourceManager.__del__ of <twain.SourceManager object at 0x004EEA10>>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\twain.py", line 2059, in __del__
  File "C:\Python34\lib\site-packages\twain.py", line 2066, in close
  File "C:\Python34\lib\_weakrefset.py", line 101, in pop
KeyError: 'pop from empty WeakSet'

Process finished with exit code 1

```
Why am I getting this error . How can I solve this ?

**Comment by denisenkom** [comment]
I pushed new version to git, try it.  I think this is caused by problem in destructor.

**Comment by yazilimci1** [comment]
I think the problem is you said in the destructor . After a document scanned probably connection will close but couldn't close connection because of while loop . I will try it thank u.
